// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sharemarketsimulation.Data;

#nullable disable

namespace Sharemarketsimulation.Migrations
{
    [DbContext(typeof(StockMarketDbContext))]
    [Migration("20251104060751_Sharemarkettable")]
    partial class Sharemarkettable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sharemarketsimulation.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitLossPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId", "StockId")
                        .IsUnique();

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AveragePrice = 170.00m,
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(139),
                            CurrentValue = 1755.00m,
                            ProfitLoss = 55.00m,
                            ProfitLossPercent = 3.24m,
                            Quantity = 10,
                            StockId = 1,
                            TotalInvestment = 1700.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AveragePrice = 140.00m,
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(142),
                            CurrentValue = 711.50m,
                            ProfitLoss = 11.50m,
                            ProfitLossPercent = 1.64m,
                            Quantity = 5,
                            StockId = 2,
                            TotalInvestment = 700.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            CompanyName = "Apple Inc.",
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(48),
                            CurrentPrice = 175.50m,
                            Description = "Technology company that designs and manufactures consumer electronics",
                            HighPrice = 176.80m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(48),
                            LowPrice = 173.90m,
                            MarketCap = 2800000000000L,
                            OpenPrice = 174.20m,
                            PreviousClose = 174.00m,
                            PriceChange = 1.50m,
                            PriceChangePercent = 0.86m,
                            Symbol = "AAPL",
                            Volume = 45000000L
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            CompanyName = "Alphabet Inc.",
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(55),
                            CurrentPrice = 142.30m,
                            Description = "Multinational technology conglomerate",
                            HighPrice = 143.20m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(55),
                            LowPrice = 140.80m,
                            MarketCap = 1800000000000L,
                            OpenPrice = 141.50m,
                            PreviousClose = 141.00m,
                            PriceChange = 1.30m,
                            PriceChangePercent = 0.92m,
                            Symbol = "GOOGL",
                            Volume = 28000000L
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            CompanyName = "Microsoft Corporation",
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(61),
                            CurrentPrice = 378.85m,
                            Description = "Multinational technology corporation",
                            HighPrice = 380.50m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(62),
                            LowPrice = 376.10m,
                            MarketCap = 2800000000000L,
                            OpenPrice = 377.20m,
                            PreviousClose = 376.50m,
                            PriceChange = 2.35m,
                            PriceChangePercent = 0.62m,
                            Symbol = "MSFT",
                            Volume = 22000000L
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            CompanyName = "Tesla Inc.",
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(67),
                            CurrentPrice = 248.50m,
                            Description = "Electric vehicle and clean energy company",
                            HighPrice = 251.20m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(68),
                            LowPrice = 244.30m,
                            MarketCap = 790000000000L,
                            OpenPrice = 245.80m,
                            PreviousClose = 246.00m,
                            PriceChange = 2.50m,
                            PriceChangePercent = 1.02m,
                            Symbol = "TSLA",
                            Volume = 35000000L
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            CompanyName = "JPMorgan Chase & Co.",
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(73),
                            CurrentPrice = 158.75m,
                            Description = "Multinational investment bank and financial services company",
                            HighPrice = 159.80m,
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(73),
                            LowPrice = 157.20m,
                            MarketCap = 465000000000L,
                            OpenPrice = 157.90m,
                            PreviousClose = 158.00m,
                            PriceChange = 0.75m,
                            PriceChangePercent = 0.47m,
                            Symbol = "JPM",
                            Volume = 12000000L
                        });
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.StockPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HighPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Date")
                        .IsUnique();

                    b.ToTable("StockPriceHistories");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commission = 5.00m,
                            NetAmount = 1705.85m,
                            Notes = "Initial purchase",
                            Price = 170.00m,
                            Quantity = 10,
                            StockId = 1,
                            Tax = 0.85m,
                            TotalAmount = 1700.00m,
                            TransactionDate = new DateTime(2025, 10, 28, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(273),
                            TransactionType = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Commission = 3.50m,
                            NetAmount = 703.85m,
                            Notes = "Google stock purchase",
                            Price = 140.00m,
                            Quantity = 5,
                            StockId = 2,
                            Tax = 0.35m,
                            TotalAmount = 700.00m,
                            TransactionDate = new DateTime(2025, 10, 30, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(285),
                            TransactionType = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KYCStatus")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000000m,
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 971, DateTimeKind.Utc).AddTicks(9319),
                            Email = "admin@stockmarket.com",
                            FirstName = "Admin",
                            IsActive = true,
                            KYCStatus = 2,
                            LastName = "User",
                            Password = "Admin@123",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Balance = 50000m,
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 971, DateTimeKind.Utc).AddTicks(9470),
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            IsActive = true,
                            KYCStatus = 2,
                            LastName = "Doe",
                            Password = "User@123",
                            PhoneNumber = "+1234567890",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Balance = 75000m,
                            CreatedAt = new DateTime(2025, 11, 4, 6, 7, 50, 971, DateTimeKind.Utc).AddTicks(9475),
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            IsActive = true,
                            KYCStatus = 2,
                            LastName = "Smith",
                            Password = "Broker@123",
                            PhoneNumber = "+1234567891",
                            Role = 3
                        });
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.UserDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileSize")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AlertPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AlertType")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlertActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId", "StockId")
                        .IsUnique();

                    b.ToTable("Watchlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(208),
                            AlertPrice = 380.00m,
                            AlertType = 1,
                            IsAlertActive = true,
                            Notes = "Buy when it crosses 380",
                            StockId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2025, 11, 4, 6, 7, 50, 972, DateTimeKind.Utc).AddTicks(211),
                            IsAlertActive = false,
                            Notes = "Monitoring Tesla for long term",
                            StockId = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Order", b =>
                {
                    b.HasOne("Sharemarketsimulation.Models.Stock", "Stock")
                        .WithMany("Orders")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sharemarketsimulation.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Portfolio", b =>
                {
                    b.HasOne("Sharemarketsimulation.Models.Stock", "Stock")
                        .WithMany("Portfolios")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sharemarketsimulation.Models.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.StockPriceHistory", b =>
                {
                    b.HasOne("Sharemarketsimulation.Models.Stock", "Stock")
                        .WithMany("PriceHistory")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Transaction", b =>
                {
                    b.HasOne("Sharemarketsimulation.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sharemarketsimulation.Models.Stock", "Stock")
                        .WithMany("Transactions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sharemarketsimulation.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.UserDocument", b =>
                {
                    b.HasOne("Sharemarketsimulation.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sharemarketsimulation.Models.User", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Watchlist", b =>
                {
                    b.HasOne("Sharemarketsimulation.Models.Stock", "Stock")
                        .WithMany("Watchlists")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sharemarketsimulation.Models.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.Stock", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Portfolios");

                    b.Navigation("PriceHistory");

                    b.Navigation("Transactions");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("Sharemarketsimulation.Models.User", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Orders");

                    b.Navigation("Portfolios");

                    b.Navigation("Transactions");

                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
